version: "3"
services:
  app:
    build:
      context: .
    depends_on:
    - db
    environment:
    - NODE_OPTIONS=-r @sprkl/obs
    - NODE_PATH=/home/.sprkl/lib/node_modules
    - SPRKL_CLI_PID=56604
    - SPRKL_LOG_LEVEL=error
    - SPRKL_PREFIX=/home/.sprkl
    - SPRKL_SERVICE_NAME=app
    ports:
    - 3333:3333
    volumes:
    - .:/home/node/app
    - sprkl-prefix-volume-0.0.42:/home/.sprkl:ro
  db:
    environment:
    - MYSQL_DATABASE=adonis
    - MYSQL_PASSWORD=adonis
    - MYSQL_ROOT_PASSWORD=adonis
    - MYSQL_USER=adonis
    - NODE_OPTIONS=-r @sprkl/obs
    - NODE_PATH=/home/.sprkl/lib/node_modules
    - SPRKL_CLI_PID=56604
    - SPRKL_LOG_LEVEL=error
    - SPRKL_PREFIX=/home/.sprkl
    - SPRKL_SERVICE_NAME=db
    image: mariadb
    ports:
    - 3306:3306
    restart: always
    volumes:
    - sprkl-prefix-volume-0.0.42:/home/.sprkl:ro
volumes:
  sprkl-prefix-volume-0.0.42:
    external: true
