version: "3"

services:
  app:
    build: 
      context: . 
    volumes:
      - .:/home/node/app 
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'adonis'
      MYSQL_PASSWORD: 'adonis'
      MYSQL_DB_NAME: 'adonis'

    ports:
      - 3333:3333 
    depends_on:
      - db 

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'adonis'
      MYSQL_USER: 'adonis'
      MYSQL_PASSWORD: 'adonis'
      MYSQL_DATABASE: 'adonis'

