version: "3"

services:
  app:
    build: 
      context: . 
    volumes:
      - .:/home/node/app 
    ports:
      - 3333:3333 
    depends_on:
      - db 

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_DATABASE: adonis

