# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        fetch-depth: 0
        
    - name: Sprkl Setup
      uses: sprkl-dev/sprkl-action/setup@master
      with:
        token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
        setenv: false

    - run: npm install
    - run: sprkl -- npm test
      env:
        APP_KEY: vWum_9TzzUl_jPpNGXYgnVODEcZ7dSUA
        DRIVE_DISK: local
        DB_CONNECTION: mysql
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306


